### DISCUSSION TITLE
How to add variables containing “.”?

### DISCUSSION THREAD

**Discussion by mrbean27123** [cgiesche/streamdeck-homeassistant#285] [Help and Support]
Normal variables are added without problems, but all where there is a point, for example “air_fryer.target_time” are not displayed, instead of them empty. Is there any way to fix this?
![Без имени](https://github.com/user-attachments/assets/dab227ea-7505-4f40-ba89-079c32979242)

And one more thing, is it possible to change the size of custom labels or put a transition to the next line in custom title to shift the variables a bit?

**Comment by mrbean27123** [comment]
After testing different objects I realized that “.” still works in some objects. So it looks like I need to write something else instead of the same air_fryer, but I don't understand what(
![image](https://github.com/user-attachments/assets/12e2cb65-1647-43d4-93cd-32298ccc71b0)

**Comment by mrbean27123** [comment]
In general, I did not find a solution, so I just added a custom version of the sensor to the file /homeassistant/configuration.yaml to display all the variables and additionally the icon changed from state to state

```
sensor:
  # Модифаед аєрогриль
  - platform: template
    sensors:
      modified_careli_maf05a_0f9c_air_fryer:
        friendly_name: "Modified Xiaomi Smart Air Fryer"
        value_template: "{{ states('sensor.careli_maf05a_0f9c_air_fryer') }}"
        attribute_templates:
          model: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'model') }}"
          lan_ip: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'lan_ip') }}"
          mac_address: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'mac_address') }}"
          entity_class: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'entity_class') }}"
          home_room: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'home_room') }}"
          exclude_miot_services: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'exclude_miot_services') }}"
          miot_type: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'miot_type') }}"
          state_property: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'state_property') }}"
          air_fryer_status: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'air_fryer.status') }}"
          air_fryer_fault: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'air_fryer.fault') }}"
          air_fryer_target_time: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'air_fryer.target_time') }}"
          air_fryer_target_temperature: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'air_fryer.target_temperature') }}"
          air_fryer_left_time: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'air_fryer.left_time') }}"
          state_updater: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'state_updater') }}"
          sub_entities: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'sub_entities') }}"
          air_fryer_status_desc: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'air_fryer.status_desc') }}"
          icon: >
            {% if states('sensor.careli_maf05a_0f9c_air_fryer') == 'unavailable' %}
              mdi:fire-alert
            {% elif states('sensor.careli_maf05a_0f9c_air_fryer') == 'cooking' %}
              mdi:fire
            {% else %}
              mdi:stove
            {% endif %}
          friendly_name: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'friendly_name') }}"
          supported_features: "{{ state_attr('sensor.careli_maf05a_0f9c_air_fryer', 'supported_features') }}"
```
