### ISSUE TITLE
Font color for Entity (custom icons) in "on" state always resets to white

### ISSUE THREAD

**Issue by dpkay** [cgiesche/streamdeck-homeassistant#270]
Hi,
Thanks for creating this super useful integration! I've been using it for about a year. A year ago I configured things properly with two icons per entity, one for the "off" state and one for the "on" state, with the text color matching the icon color.

Today I upgraded to 2.4.5, but it appears that I can no longer set the text color in the "on" state of the entity. After hitting OK in the color picker dialog, the color still changes in the UI, but once the little text format popup closes, the color resets to white. This is not the case for the "off" state of the entity (where it works correctly), and it also wasn't the case a year ago when I initially set up my config. Unfortunately I don't have a record of what plugin version I was on back then, but I hope that narrows down finding the root cause.

![Untitled-1](https://github.com/cgiesche/streamdeck-homeassistant/assets/379402/58aef160-3cc1-4cc7-8aed-8ac470a7bc42)

**Comment by cgiesche** [comment]
Hi,

thank you very much for your feedback :)

The "title feature" is provided by the stream deck application and not related to my plugin. I can confirm the title color changes to white for "on" states but this seems to be a stream deck bug.

**Comment by fkthisusrrequirement** [comment]
Sorry to reopen this.
I've been trying to change the colors of icons for a long time; I haven't been able to. This topic shows it's possible. Can I have some pointers please?

**Comment by cgiesche** [comment]
Hi,

in the above screenshot, the icons are in fact images (using the "Entity (custom icons)" plugin). I personally do not like this because you lose a lot of flexibility (only on/off supported, no labels to display live data like temperature etc.).

There is a way to color icons based on their state or class but this is not completely trivial because it includes editing yml files. I will try to explain with an example.
Let's say you want these windows and doors to be colored differently:

![Image](https://github.com/user-attachments/assets/803c7c91-5fc9-41b7-b394-46467c09b623)

- Download the current default display config from this reopo: https://raw.githubusercontent.com/cgiesche/streamdeck-homeassistant/refs/heads/master/public/config/default-display-config.yml
- Save this file as "custom-theme.yml" in a folder on your disk.
- Enter this file as custom display config in the plugin and press "Save and reconnect". After that everything should look like before and no error should be displayed.
![Image](https://github.com/user-attachments/assets/4d130e82-c147-4f87-bb2b-c13a5d49fd02)

- Open the file in an text editor of your choice
- In my case, i want to customize "window" which is a class of "binary_sensor". So i search for that in the config and find the following
```
binary_sensor:
  labelTemplates:
  icon: mdi:radiobox-blank
  states:
    on:
      icon: mdi:radiobox-marked
  classes:
    plug:
      icon: mdi:power-plug-off-outline
      states:
        on:
          icon: mdi:power-plug-outline
    window:
      icon: mdi:window-closed-variant
      states:
        on:
          icon: mdi:window-open-variant
    door:
      icon: mdi:door-closed
      states:
        on:
          icon: mdi:door-open
    motion:
      icon: mdi:motion-sensor
      states:
        off:
          icon: mdi:motion-sensor-off
```

Now, you can edit the color of the icon in general (Press "save and reconnect" in plugin to see changes):
```
    window:
      color: '#0000FF'
      icon: mdi:window-closed-variant
      states:
        on:
          icon: mdi:window-open-variant
```

![Image](https://github.com/user-attachments/assets/245f2fc5-761f-46e0-a341-f97897cccaf4)

You can also overwrite the color for a specific state  (Press "save and reconnect" in plugin to see changes):
```
    window:
      color: '#0000FF'
      icon: mdi:window-closed-variant
      states:
        on:
          color: '#FF0000'
          icon: mdi:window-open-variant
```

![Image](https://github.com/user-attachments/assets/9d04b7df-a49a-4f6f-9f32-af366db65607)

Just be careful: The indentation of the lines is very important. Messing that up may lead to everything not working :)
