### ISSUE TITLE
shell_command doesn't display items

### ISSUE THREAD

**Issue by miklos-szel** [cgiesche/streamdeck-homeassistant#327]
![image](https://github.com/user-attachments/assets/fab4c8c0-b4d1-4506-b65f-015f76846173)
![image](https://github.com/user-attachments/assets/f2033cb5-b1bd-41e6-8a86-b8b3ded5960f)

I have the following shell_commands in HA:
```
shell_command:
  wiim_preset_1: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:1'
  wiim_preset_2: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:2'
  wiim_preset_3: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:3'
  wiim_preset_4: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:4'
  wiim_preset_5: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:5'
  wiim_preset_6: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:6'
  wiim_preset_7: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:7'
  wiim_preset_8: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:8'
  wiim_preset_9: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:9'
  wiim_prev: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=setPlayerCmd:prev'
  wiim_toggle: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=setPlayerCmd:onepause'
  wiim_next: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=setPlayerCmd:next'
  wiim_volup: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=setPlayerCmd:vol%2b%2b'
  wiim_voldn: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=setPlayerCmd:vol--'
  wiim_office_preset_1: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:1'
  wiim_office_preset_2: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:2'
  wiim_office_preset_3: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:3'
  wiim_office_preset_4: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:4'
  wiim_office_preset_5: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:5'
  wiim_office_preset_6: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:6'
  wiim_office_preset_7: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:7'
  wiim_office_preset_8: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:8'
  wiim_office_preset_9: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:9'
  wiim_office_preset_10: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:10'
  wiim_office_preset_11: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:11'
  wiim_office_preset_12: 'curl -k https://192.168.xxx.xxx/httpapi.asp?command=MCUKeyShortClick:12'


```

I can see the number of elements listed in the plugin, they work as well, but their name is not displayed.
