### ISSUE TITLE
Allow multiple entities to be selected/specified

### ISSUE THREAD

**Issue by vertex-github** [cgiesche/streamdeck-homeassistant#70]
Please allow multiple entities to be be specified for the same domain so that I can easily switch multiple switches or lights from a single key

**Comment by linickx** [comment]
Hello, This can be done already...

In HA, create an [input_boolean](https://www.home-assistant.io/integrations/input_boolean/) helper (Under Configuration -> Helpers)

Create 2x automations that fire when the state changes, one for on, one for off ... here's an off example...

```
alias: Stream Deck Off Switch
trigger:
  - platform: state
    entity_id: input_boolean.office_kill_switch
    from: 'on'
    to: 'off'
condition: []
action:
  - type: turn_off
    device_id: abc123
    entity_id: light.office_light
    domain: light
  - type: turn_off
    device_id: 123abc
    entity_id: switch.office_plug1
    domain: switch
mode: single
```

In stream deck, create a HA button.

- Domain -> input_boolean
- Entity -> office_kill_switch (or whatever!)
- Service -> Toggle

HTH!
